display_name: PSG

packager: Publishing Society Group
packagerEmail: wainixueer3334@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - PSG
  - Proxy
  - ClashMeta

generic_name: PSG

group: Applications/Internet

startup_notify: true