script_template: inno_setup.iss
app_id: 728B3532-C74B-4870-9068-BE70FE12A3E6
app_name: PSG
publisher: Publishing Society Group
publisher_url: https://github.com/WENSHAO521/FlClash-
display_name: PSG
executable_name: PSG.exe
output_base_file_name: PSG.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin